apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-e2e.1.0.0-17
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-cd-e2e.1.0.0-17
  template:
    metadata:
      labels:
        app: ci-cd-e2e.1.0.0-17
    spec:
      containers:
        - name: ci-cd-e2e.1.0.0-17
          image: baretsky24/ci-cd-e2e.1.0.0-17
          ressources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
